/********************************************************************
* neutrinoSpecialAttention_nuSpecAttPackageDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error neutrinoSpecialAttention_nuSpecAttPackageDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableneutrinoSpecialAttention_nuSpecAttPackageDict();
extern void G__cpp_setup_inheritanceneutrinoSpecialAttention_nuSpecAttPackageDict();
extern void G__cpp_setup_typetableneutrinoSpecialAttention_nuSpecAttPackageDict();
extern void G__cpp_setup_memvarneutrinoSpecialAttention_nuSpecAttPackageDict();
extern void G__cpp_setup_globalneutrinoSpecialAttention_nuSpecAttPackageDict();
extern void G__cpp_setup_memfuncneutrinoSpecialAttention_nuSpecAttPackageDict();
extern void G__cpp_setup_funcneutrinoSpecialAttention_nuSpecAttPackageDict();
extern void G__set_cpp_environmentneutrinoSpecialAttention_nuSpecAttPackageDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "sample.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__neutrinoSpecialAttention_nuSpecAttPackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__neutrinoSpecialAttention_nuSpecAttPackageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__neutrinoSpecialAttention_nuSpecAttPackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__neutrinoSpecialAttention_nuSpecAttPackageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__neutrinoSpecialAttention_nuSpecAttPackageDictLN_sample;

/* STUB derived class for protected member access */
